/*
 *
 * Copyright (c) 2011 by Steve Devore
 *                       http://bookscanwizard.sourceforge.net
 *
 * This file is part of the Book Scan Wizard.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

package net.sourceforge.bookscanwizard;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.sourceforge.bookscanwizard.op.SaveToArchive;

/**
 *
 * @author Steve
 */
public class UploadFile extends javax.swing.JDialog {
    private static UploadFile instance;

    static void upload(ActionListener menuHandler) throws Exception {
        UploadFile uploadFile = new UploadFile(BSW.instance().getMainFrame(), true, menuHandler);
        uploadFile.setVisible(true);
    }

    public void performUpload() throws Exception {
        SaveToArchive.saveToArchive(jFile.getSelectedFile().getPath(), jAccess.getText(), jSecret.getText());
    }

    /** Creates new form UploadFile */
    public UploadFile(java.awt.Frame parent, boolean modal, final ActionListener menuHandler) throws Exception {
        super(parent, modal);
        initComponents();
        jFile.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                UploadFile.this.dispose();
                if (JFileChooser.APPROVE_SELECTION.equals(e.getActionCommand())) {
                    System.out.println(e.getSource());
                    ActionEvent event = new ActionEvent(e.getSource(), e.getID(), "do_upload");
                    menuHandler.actionPerformed(event);
                }
            }
        });
        String fileName = null;
        Operation.getOperations(BSW.instance().getMainFrame().getConfigEntry().getText());
        if (SaveToArchive.getLastSave() != null) {
            jAccess.setText(SaveToArchive.getLastSave().getAccess());
            jSecret.setText(SaveToArchive.getLastSave().getSecret());
            fileName = SaveToArchive.getLastSave().getFileName();
        }
        if (fileName == null) {
            fileName = "archive.zip";
        }
        jFile.setSelectedFile(new File(BSW.getCurrentDirectory(), fileName));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jAccess = new javax.swing.JTextField();
        jSecret = new javax.swing.JTextField();
        jFile = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Upload file to archive.org");
        setModal(true);

        jLabel1.setText("Access Key:");

        jLabel2.setText("Secret Key:");

        jAccess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAccessActionPerformed(evt);
            }
        });

        jFile.setApproveButtonText("Upload");
        jFile.setCurrentDirectory(BSW.getCurrentDirectory());
        jFile.setDialogTitle("Choose the Zip file to Upload");
        jFile.setFileFilter(new FileNameExtensionFilter("Archive Zip Files", "zip"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSecret)
                    .addComponent(jAccess, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                .addGap(439, 439, 439))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAccess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSecret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAccessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAccessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAccessActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UploadFile dialog = new UploadFile(new javax.swing.JFrame(), true, null);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(UploadFile.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAccess;
    private javax.swing.JFileChooser jFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jSecret;
    // End of variables declaration//GEN-END:variables

}
